### ISSUE TITLE
Error on disconect

### ISSUE THREAD

**Issue by Malachiel87** [GhastD/JI-Issues#2]
**Describe the bug**
Error or disconections

**To Reproduce**
Just installed a fresh JL and restarted, it trow error everyime player quit. 

**Versioning (please complete the following information):**
 - Player Version: 1.12.2
 - Server Version: 1.12.2
 - Server Jar: Paper

**Additional context**

**Log**
https://gist.github.com/xion87/0358ac3aea7db0bc15094b707cf085f7
https://gist.github.com/xion87/4f1ac9c0a756d6cc683558c9bb012224

**Contact info**
Discord: Malachiel#8561

**Comment by terminalsin** [comment]
Fixed: https://www.mc-market.org/resources/2442/update?update=41689
