### ISSUE TITLE
JI - Bug Report

### ISSUE THREAD

**Issue by MynamisTG** [GhastD/JI-Issues#3]
**Describe the bug**
Error: Asynchronous player kick - in console cannot ban player!

![image](https://user-images.githubusercontent.com/50236996/76453390-61fff580-6405-11ea-92ce-c522b2fbd9f5.png)

Version: JI anticheat 5.7-2
Version server : Paper spigot 1.8.x

**Comment by terminalsin** [comment]
Fixed: https://www.mc-market.org/resources/2442/update?update=41689
