### ISSUE TITLE
JI - Feature Request (Support to Lazarus)

### ISSUE THREAD

**Issue by TitoVala** [GhastD/JI-Issues#5]
**Is your feature request related to a problem? Please describe.**
- Yes, because I need support for Lazarus, I'm using a old version of JI to work with Lazarus

**Describe the solution you'd like**
- Support with Lazarus.

**Describe alternatives you've considered**
- No

**Additional context**
- Nothing, thank you

**Comment by terminalsin** [comment]
What's not working with Lazarus?
